server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: blog

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: fuhongjun.233

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: fuhongjun.233
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# MyBatis Plus配置
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰命名
    map-underscore-to-camel-case: true
  # 实体类扫描
  type-aliases-package: com.shymoy.entity
  # mapper xml文件位置
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      # 主键策略
      id-type: auto
      # 逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT配置
jwt:
  secret: shymoy-blog-secret-key-2025-very-long-secret-key-for-security
  expiration: 604800000 # 7天，单位毫秒

# 日志配置
logging:
  level:
    com.shymoy: debug
    org.springframework: info
